spring.application.name=Patient-Service
server.port=4000

spring.profiles.active=local
#ddl-auto=validate here ? not update, not create ? is deliberate:
#Hibernate only checks your entities match what Flyway already built;
#it never touches schema itself, in either dev or prod. Only Flyway owns schema changes now.

#spring.jpa.open-in-view=false
#spring.jpa.hibernate.ddl-auto=validate
#
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration

# ==========================================================
# SpringDoc OpenAPI / Swagger UI Configuration
# ==========================================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
